### ISSUE TITLE
"Prolog" option duality

### ISSUE THREAD

**Issue by gdelfino** [antononcube/WL-MermaidJS-paclet#2]
I use Linux with bash. So the hardcoded default "Prolog"->"~.zshrc" doesn't work well for me. Also, in order to have a nodejs that is not too old, I installed a fresh nodejs using nvm. In order for this to be recognized, I have found that I can provide a "Prolog" -> "source ~/.nvm/nvm.sh" option. The problem is that "Prolog" is also an option for Graphics so when I generate a diagram in "PDF" format, the option is also sent to the resulting Graphic resulting in a error.

**Comment by antononcube** [comment]
Thank you for your interest in this paclet!
I will review and test your proposed changes and submit a new paclet version soon.

**Comment by antononcube** [comment]
Sorry, for my delayed response... 

`MermaidJS` has the option `"ShellSession" -> Automatic`. I think it is more consistent the to change "Prolog" into "ShellSessionProlog". What do you think?

**Comment by antononcube** [comment]
This issue should be fixed in the version 1.0.5 of the [paclet](https://resources.wolframcloud.com/PacletRepository/resources/AntonAntonov/MermaidJS).
